### PR TITLE
Create and read article

### PR DESCRIPTION
**Pull request by FranDepascuali**
## Sumary

Articles can now be created and read. 

**Trello cards**:
https://trello.com/c/jqvFYoZM/24-crear-blog-base
## Test Plan
- Open a terminal.
- Go to project directory.
- Run ./bin/rails server.
- Open browser and go to http://localhost:3000/articles/new to create a new article.
- Go to http://localhost:3000/articles/ to see all articles.
## Screenshots

create-read-article
listing-articles

### CODE REVIEW

**Comment by FranDepascuali** [comment]
@NicoBuch

**Comment by FranDepascuali** [comment]
@NicoBuch

**Comment by FranDepascuali** [comment]
@NicoBuch

**Comment by NicoBuch** [comment]
:+1:

**Pull request merged**
