### PR TITLE
Article title and text can now be edited

### PR DESCRIPTION
**Pull request by FranDepascuali**
## Sumary

Articles can now be edited.

**Trello cards**:
https://trello.com/c/jqvFYoZM/24-crear-blog-base
## Test Plan
- Open a terminal.
- Go to project directory.
- Run ./bin/rails server.
- Open browser and go to http://localhost:3000/articles/.
- Click in show to view item in detail, or edit to change item's title or description.
## Screenshots

editing-articles

### CODE REVIEW

**Comment by FranDepascuali** [comment]
@NicoBuch

**Comment by FranDepascuali** [comment]
@NicoBuch

**Comment by NicoBuch** [comment]
@FranDepascuali Check out identations (rubocop will do it automatically with -a) and then merge it. :+1:

**Comment by NicoBuch** [comment]
@FranDepascuali For next time, do not amend commits (I assume it was with rebase) until PR is approved

**Pull request closed without merging**
